# Welcome to Late Night SMP Plugin Config!
# Here you can do a lot of config!

monthly-event:
  counter:
    track-counter: "statistic_jump"
    leaderboard-display: "Jumping"

event:
  event-running: false
  is-community-goal: false

  event-name: "Coming soon..."
  event-details: ""
  # Event Type: EFFECT,
  event-type: "EFFECT"
  # Depending on event-type
  # EFFECT: moon-gravity, fortune-drop
  impact: ""
  duration: 300 # In seconds

  # If is-community-goal: true

features:
  elytra:
    is-ban: true
    message: "&cSorry no elytra uses in this server :("

# END