name: LateNightSMPPlugin2612
version: '${version}'

main: io.github.nurjavier8789.lateNightSMPPlugin2612.LateNightSMPPlugin2612
api-version: '26.1.2'
load: POSTWORLD

commands:
  latenightsmpplugin:
    description: Late Night SMP Plugin Command!
    permission: latenightsmpplugin
    aliases: [lnsmpp]
  chat:
    description: Send a chat to different channel!
    usage: /chat <channel> [msg]
